version: "3.8"

services:

  localstack:
    container_name: localstack_studying
    image: localstack/localstack:latest
    environment: 
      - SERVICES=s3,lambda,logs,dynamodb,sqs
      - DEBUG=1
    ports:
      - "127.0.0.1:7566:4566"
      - "127.0.0.1:7571:4571"